#!/usr/bin/env python3
from __future__ import annotations
import argparse, base64, os, secrets
from pathlib import Path

TEMPLATE = """# Generated by LoopGrid v0.8 Design Partner Release. Do not commit this file.\nLOOPGRID_POSTGRES_PASSWORD={postgres_password}\nLOOPGRID_PLATFORM_ADMIN_KEY={platform_admin_key}\nLOOPGRID_BOOTSTRAP_TOKEN={bootstrap_token}\nLOOPGRID_PAYLOAD_MASTER_KEY_B64={payload_key}\n\nLOOPGRID_ENV=production\nLOOPGRID_PUBLIC_BASE_URL=http://localhost:8000\nLOOPGRID_REQUIRE_USER_AUTH=true\nLOOPGRID_STRICT_PRODUCTION_SAFETY=true\nLOOPGRID_ENFORCE_LIFECYCLE=true\nLOOPGRID_CORS_ORIGINS=\n\nLOOPGRID_SIGNER_PROVIDER=local_ed25519\nLOOPGRID_TSA_URL=\nLOOPGRID_TSA_CA_FILE=\nLOOPGRID_MCP_UPSTREAMS_JSON={{}}\n\nLOOPGRID_DB_POOL_SIZE=10\nLOOPGRID_DB_MAX_OVERFLOW=20\nLOOPGRID_DB_POOL_RECYCLE_SECONDS=1800\nLOOPGRID_MAX_REQUEST_BODY_BYTES=2000000\nLOOPGRID_INGEST_RATE_LIMIT_PER_MINUTE=600\nLOOPGRID_ADMIN_RATE_LIMIT_PER_MINUTE=120\n"""

def main():
    ap=argparse.ArgumentParser(description="Generate strong local secrets for the LoopGrid v0.8 Docker design-partner deployment")
    ap.add_argument("--output",default=".env")
    ap.add_argument("--force",action="store_true")
    args=ap.parse_args()
    out=Path(args.output)
    if out.exists() and not args.force:
        raise SystemExit(f"{out} already exists. Refusing to overwrite; use --force only if you intend to rotate local deployment secrets.")
    text=TEMPLATE.format(
        postgres_password=secrets.token_urlsafe(32),
        platform_admin_key="lg_platform_"+secrets.token_urlsafe(36),
        bootstrap_token="lg_bootstrap_"+secrets.token_urlsafe(36),
        payload_key=base64.b64encode(os.urandom(32)).decode("ascii"),
    )
    out.write_text(text,encoding="utf-8")
    try: os.chmod(out,0o600)
    except OSError: pass
    print(f"Created {out} with generated local deployment secrets.")
    print("Secrets were not printed. Keep this file private and do not commit it.")
    print("Next: docker compose up --build -d")

if __name__=="__main__":main()
