from __future__ import annotations
import argparse, json, os, sys, time
from pathlib import Path
import httpx

ap=argparse.ArgumentParser(description='LoopGrid v0.8 MCP Evidence Gateway release gate')
ap.add_argument('--base-url',default='http://127.0.0.1:8000')
ap.add_argument('--workspace',default='default')
a=ap.parse_args()
base=a.base_url.rstrip('/')
workspace=a.workspace

def fail(name,detail):
    print(f'[FAIL] {name} - {detail}')
    raise SystemExit(1)
def ok(name,detail=''):
    print(f'[PASS] {name}' + (f' - {detail}' if detail else ''))
def req(method,path,**kw):
    try:
        return httpx.request(method,base+path,timeout=20,**kw)
    except Exception as e:
        fail(path,f'{type(e).__name__}: {e}')

r=req('GET','/health')
if r.status_code!=200: fail('Server health',f'HTTP {r.status_code}')
ok('Server health',r.json().get('version','unknown'))

info=req('GET','/api/v1/system/info')
if info.status_code!=200: fail('System info',f'HTTP {info.status_code}')
mi=(info.json().get('mcp_proxy') or {})
if not mi.get('enabled') or 'billing' not in (mi.get('configured_aliases') or []):
    fail('MCP allow-list configuration',json.dumps(mi))
ok('MCP allow-list configuration','billing -> configured upstream')

# In development/no-auth mode this is intentionally allowed as a local bootstrap path.
# In auth-required mode auth-required deployments should reject anonymous issuance; for this gate use the
# dedicated local mcp-test.db instructions so we can bootstrap disposable scoped keys.
issue=req('POST',f'/api/v1/workspaces/{workspace}/keys',json={
    'name':'mcp-gateway-test','description':'Disposable local MCP gateway validation key',
    'scopes':['ingest','read']
})
if issue.status_code!=200:
    fail('Scoped MCP test key issued',f'HTTP {issue.status_code}: {issue.text[:300]}')
key=issue.json()['api_key']; kid=issue.json()['key_id']
headers={'X-LoopGrid-Key':key,'Content-Type':'application/json'}
ok('Scoped MCP test key issued',kid)

bad=req('POST','/api/v1/mcp-proxy/not-configured',headers=headers,json={'jsonrpc':'2.0','id':'blocked','method':'tools/list'})
if bad.status_code!=404 or 'arbitrary URLs' not in bad.text:
    fail('Arbitrary/unconfigured MCP target rejected',f'HTTP {bad.status_code}: {bad.text[:300]}')
ok('Arbitrary/unconfigured MCP target rejected','HTTP 404')

lst=req('POST','/api/v1/mcp-proxy/billing',headers=headers,json={'jsonrpc':'2.0','id':'list-1','method':'tools/list'})
if lst.status_code!=200: fail('MCP tools/list proxied',f'HTTP {lst.status_code}: {lst.text[:300]}')
lj=lst.json(); tools=((lj.get('result') or {}).get('tools') or [])
if not any(t.get('name')=='refund' for t in tools): fail('MCP tools/list proxied',json.dumps(lj))
ok('MCP tools/list proxied','refund tool discovered')

call_body={'jsonrpc':'2.0','id':'call-1','method':'tools/call','params':{'name':'refund','arguments':{'amount':20,'currency':'USD'}}}
call=req('POST','/api/v1/mcp-proxy/billing',headers={**headers,'X-LoopGrid-Agent':'mcp-test-agent','traceparent':'00-1234567890abcdef1234567890abcdef-1234567890abcdef-01'},json=call_body)
if call.status_code!=200: fail('MCP tools/call proxied',f'HTTP {call.status_code}: {call.text[:300]}')
cj=call.json(); result=cj.get('result') or {}
if result.get('external_reference')!='mcp_test_001' or result.get('tool')!='refund': fail('MCP tools/call proxied',json.dumps(cj))
ok('MCP tools/call proxied','external_reference=mcp_test_001')

# Find the evidence record generated by the proxied call.
dec=req('GET',f'/api/v1/decisions?workspace_id={workspace}&limit=50',headers={'X-LoopGrid-Key':key})
if dec.status_code!=200: fail('Read MCP evidence register',f'HTTP {dec.status_code}')
rows=dec.json()
match=next((d for d in rows if d.get('decision_type')=='mcp_tool_call' and d.get('service_name')=='mcp-proxy:billing' and (d.get('agent') or {}).get('id')=='mcp-test-agent'),None)
if not match: fail('MCP evidence record created','no matching mcp-proxy:billing decision found')
did=match['decision_id'];ok('MCP evidence record created',did)

detail=req('GET',f'/api/v1/decisions/{did}',headers={'X-LoopGrid-Key':key})
if detail.status_code!=200: fail('Investigate MCP evidence',f'HTTP {detail.status_code}')
dj=detail.json(); ets=[e.get('event_type') for e in dj.get('events',[])]
required={'decision_created','mcp_tool_requested','mcp_tool_result','outcome_observed'}
missing=sorted(required-set(ets))
if missing: fail('MCP request/result/outcome captured',f'missing={missing}; events={ets}')
out=(dj.get('summary') or {}).get('outcome') or {}
if out.get('status')!='succeeded': fail('MCP request/result/outcome captured',json.dumps(out))
ok('MCP request/result/outcome captured','request + result + observed outcome')

ver=req('GET',f'/api/v1/decisions/{did}/verify',headers={'X-LoopGrid-Key':key})
if ver.status_code!=200 or not ver.json().get('valid'):
    fail('MCP evidence cryptographic verification',f'HTTP {ver.status_code}: {ver.text[:300]}')
ok('MCP evidence cryptographic verification',f"events={ver.json().get('events_checked',ver.json().get('events','?'))}")

# Ensure the proxy does not accidentally expose admin/read privileges through the ingest path.
admin=req('GET',f'/api/v1/workspaces/{workspace}/keys',headers={'X-LoopGrid-Key':key})
if admin.status_code not in (401,403): fail('MCP service key least privilege',f'expected 401/403, got {admin.status_code}')
ok('MCP service key least privilege',f'admin endpoint HTTP {admin.status_code}')

print('\nMCP EVIDENCE GATEWAY VALIDATION RESULT: PASS')
print(f'Decision: {did}')
